# Generated by Django 6.0.5 on 2026-05-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korean_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(max_length=100)),
                ('malicious_payload', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
