# Generated by Django 6.0.5 on 2026-06-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korean_app', '0003_category_guestbookcomment_userprofilereview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityIncidentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('flagged_username', models.CharField(max_length=100)),
                ('flagged_comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GuestBookComment',
        ),
    ]
