# Generated by Django 6.0.5 on 2026-07-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korean_app', '0004_guestbookentry_securityincidentlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='image_filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
